CREATE TABLE ACCOUNT (
    ID          BIGINT          PRIMARY KEY AUTO_INCREMENT,
    AMOUNT      DECIMAL(12,2)   NOT NULL,
    CURRENCY    SMALLINT        NOT NULL,
    USER_ID     BIGINT          NOT NULL
);

ALTER TABLE ACCOUNT ADD FOREIGN KEY (USER_ID) REFERENCES USER(ID);