ALTER TABLE USER
    ADD COLUMN UUID VARCHAR(36)     NOT NULL    UNIQUE     AFTER ID;

ALTER TABLE ACCOUNT
    ADD COLUMN UUID VARCHAR(36)     NOT NULL    UNIQUE     AFTER ID;

ALTER TABLE TRANSACTION
    ADD COLUMN UUID VARCHAR(36)     NOT NULL    UNIQUE     AFTER ID;